apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisfe
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: redisfe
  template:
    metadata:
      labels:
        app: redisfe
    spec:
      containers:
        - name: redisfe
          image: registry.hub.docker.com/idanatias/redis-fe:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 7042
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
